// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2dgWyADzSsKlqjo3c8H-IO9_shrdm4ZE',
    appId: '1:770968608350:web:fdcd557f5f5d9c72599ecf',
    messagingSenderId: '770968608350',
    projectId: 'shopby-3133c',
    authDomain: 'shopby-3133c.firebaseapp.com',
    storageBucket: 'shopby-3133c.firebasestorage.app',
    measurementId: 'G-GH9WC5CKWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lC812kvgo2qan3jjmXkXGwGIFxphm1k',
    appId: '1:770968608350:android:434a79cecb2cbdcd599ecf',
    messagingSenderId: '770968608350',
    projectId: 'shopby-3133c',
    storageBucket: 'shopby-3133c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASa9tCQ6xXZfiQ0WqmIlGpdf32Wc0h-GY',
    appId: '1:770968608350:ios:28ee67499525b3e6599ecf',
    messagingSenderId: '770968608350',
    projectId: 'shopby-3133c',
    storageBucket: 'shopby-3133c.firebasestorage.app',
    iosBundleId: 'com.example.shopby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASa9tCQ6xXZfiQ0WqmIlGpdf32Wc0h-GY',
    appId: '1:770968608350:ios:28ee67499525b3e6599ecf',
    messagingSenderId: '770968608350',
    projectId: 'shopby-3133c',
    storageBucket: 'shopby-3133c.firebasestorage.app',
    iosBundleId: 'com.example.shopby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2dgWyADzSsKlqjo3c8H-IO9_shrdm4ZE',
    appId: '1:770968608350:web:bbc71b3a019268b6599ecf',
    messagingSenderId: '770968608350',
    projectId: 'shopby-3133c',
    authDomain: 'shopby-3133c.firebaseapp.com',
    storageBucket: 'shopby-3133c.firebasestorage.app',
    measurementId: 'G-LG06JSHJ91',
  );
}
